export const productos = [
  {
    _id: "1",
    vendedor: "Juan Pérez",
    titulo: "Laptop Gamer Pro",
    descripcion:
      "Laptop de alta gama con procesador Intel i7, 16GB RAM, RTX 3060",
    precio: 150000,
    moneda: "ARS",
    activo: true,
    stock: 2,
    ventas: 25,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Laptop+Gamer"],
  },
  {
    _id: "2",
    vendedor: "Juan Pérez",
    titulo: "Auriculares Bluetooth",
    descripcion: "Auriculares inalámbricos con cancelación de ruido activa",
    precio: 25000,
    moneda: "ARS",
    activo: true,
    stock: 50,
    ventas: 100,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Auriculares"],
  },
  {
    _id: "3",
    vendedor: "María García",
    titulo: "Teclado Mecánico RGB",
    descripcion:
      "Teclado mecánico gaming con switches Cherry MX Red e iluminación RGB",
    precio: 35000,
    moneda: "ARS",
    activo: true,
    stock: 0,
    ventas: 45,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Teclado"],
  },
  {
    _id: "4",
    vendedor: "María García",
    titulo: "Mouse Gamer Inalámbrico",
    descripcion:
      "Mouse gaming de alta precisión con sensor óptico de 16000 DPI",
    precio: 18000,
    moneda: "ARS",
    activo: true,
    stock: 40,
    ventas: 80,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Mouse"],
  },
  {
    _id: "5",
    vendedor: "Carlos López",
    titulo: "Monitor 27 pulgadas 144Hz",
    descripcion:
      "Monitor gaming Full HD con tasa de refresco de 144Hz y 1ms de respuesta",
    precio: 95000,
    moneda: "ARS",
    activo: true,
    stock: 15,
    ventas: 30,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Monitor"],
  },
  {
    _id: "6",
    vendedor: "Carlos López",
    titulo: "Silla Gamer Ergonómica",
    descripcion:
      "Silla gamer con soporte lumbar, reposabrazos ajustables y reclinación 180°",
    precio: 85000,
    moneda: "ARS",
    activo: true,
    stock: 20,
    ventas: 15,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Silla"],
  },
  {
    _id: "7",
    vendedor: "Juan Pérez",
    titulo: "Webcam Full HD",
    descripcion:
      "Cámara web 1080p con micrófono incorporado y enfoque automático",
    precio: 22000,
    moneda: "ARS",
    activo: true,
    stock: 35,
    ventas: 60,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Webcam"],
  },
  {
    _id: "8",
    vendedor: "María García",
    titulo: "Micrófono USB Profesional",
    descripcion:
      "Micrófono de condensador USB con soporte anti-vibración y filtro pop",
    precio: 45000,
    moneda: "ARS",
    activo: true,
    stock: 25,
    ventas: 40,
    categorias: [],
    fotos: ["https://via.placeholder.com/400x400?text=Microfono"],
  },
];
